import '../models/question_model.dart';

List<Question> who5Questions = [
  Question(
    id: 1,
    questionText: "Today, I felt cheerful and in a good mood.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 2,
    questionText: "Today, I felt calm and relaxed.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 3,
    questionText: "Today, I felt energetic and active.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 4,
    questionText: "Today, I felt fresh and well-rested.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 5,
    questionText: "Today, I found interest in what I was doing.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 6,
    questionText: "Today, I felt confident handling my tasks.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 7,
    questionText: "Today, I felt satisfied with my day.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 8,
    questionText: "Today, I felt emotionally stable.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 9,
    questionText: "Today, I felt positive about things.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
  Question(
    id: 10,
    questionText: "Today, I felt mentally clear and focused.",
    category: "who5",
    options: [
      Option(text: "Not at all", value: 0),
      Option(text: "A little", value: 1),
      Option(text: "Sometimes", value: 2),
      Option(text: "Often", value: 3),
      Option(text: "Most of the time", value: 4),
      Option(text: "All the time", value: 5),
    ],
  ),
];